### PR TITLE
Add traits docs

### PR DESCRIPTION
**Pull request by gadelkareem**

### CODE REVIEW

**Comment by l3pp4rd** [comment]
thanks ;)

**Comment by l3pp4rd** [comment]
ah, you should have opened a pull request on https://github.com/Atlantic18/DoctrineExtensions this repository was moved some time ago

**Comment by l3pp4rd** [comment]
have picked the commit to other repo, in the future open it there ;)

**Comment by gadelkareem** [comment]
Ah glad it is merged. Thank you!

**Pull request merged**
